version: '3.9'

volumes:
  mariadb:

services:

  db:
    image: mariadb
    container_name: mariadb_container
    restart: always
    ports:
      - '6033:3306'
    volumes:
      - mariadb:/var/lib/mysql
      - ./src/main/resources/db/migration/dbinit/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root

  phphmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    depends_on:
      - db
    ports:
      - '9999:80'
    environment:
      - PMA_HOST=db


