insert into book (id, name, is_available, author_id) values (1, 'Gate, The', false, 61);
insert into book (id, name, is_available, author_id) values (2, '17 Again', false, 234);
insert into book (id, name, is_available, author_id) values (3, 'Horror Business', true, 336);
insert into book (id, name, is_available, author_id) values (4, 'Son of the Pink Panther', true, 467);
insert into book (id, name, is_available, author_id) values (5, 'Nell', true, 226);
insert into book (id, name, is_available, author_id) values (6, 'Diary of a Shinjuku Thief (Shinjuku dorobo nikki)', false, 88);
insert into book (id, name, is_available, author_id) values (7, 'FC Venus', true, 165);
insert into book (id, name, is_available, author_id) values (8, 'Bright Lights, Big City', true, 296);
insert into book (id, name, is_available, author_id) values (9, 'Shakes the Clown', false, 159);
insert into book (id, name, is_available, author_id) values (10, 'Razorback', false, 344);
insert into book (id, name, is_available, author_id) values (11, 'Apple, The', false, 250);
insert into book (id, name, is_available, author_id) values (12, 'Get2Gether, A', false, 378);
insert into book (id, name, is_available, author_id) values (13, 'Imago mortis', true, 312);
insert into book (id, name, is_available, author_id) values (14, 'Tapia', false, 126);
insert into book (id, name, is_available, author_id) values (15, 'Home', true, 253);
insert into book (id, name, is_available, author_id) values (16, 'Horton Hears a Who!', false, 330);
insert into book (id, name, is_available, author_id) values (17, 'Non-Stop', true, 391);
insert into book (id, name, is_available, author_id) values (18, 'Sweet November', true, 297);
insert into book (id, name, is_available, author_id) values (19, 'Lorna''s Silence (Le silence de Lorna)', true, 154);
insert into book (id, name, is_available, author_id) values (20, 'Two English Girls (Les deux anglaises et le continent)', false, 113);
insert into book (id, name, is_available, author_id) values (21, 'Kull the Conqueror', true, 186);
insert into book (id, name, is_available, author_id) values (22, 'Apache', false, 8);
insert into book (id, name, is_available, author_id) values (23, 'Monsturd', false, 6);
insert into book (id, name, is_available, author_id) values (24, '11 Flowers (Wo 11)', true, 315);
insert into book (id, name, is_available, author_id) values (25, 'Lips of Blood (Lèvres de sang)', false, 176);
insert into book (id, name, is_available, author_id) values (26, 'Ghostmaker, The (Box of Shadows)', false, 196);
insert into book (id, name, is_available, author_id) values (27, 'Electra Glide in Blue', false, 248);
insert into book (id, name, is_available, author_id) values (28, 'Fluffer, The', true, 119);
insert into book (id, name, is_available, author_id) values (29, 'Happy Accidents', false, 11);
insert into book (id, name, is_available, author_id) values (30, 'Night of the Shooting Stars (Notte di San Lorenzo, La)', false, 430);
insert into book (id, name, is_available, author_id) values (31, 'Mountain Patrol (Kekexili)', true, 446);
insert into book (id, name, is_available, author_id) values (32, 'Slim Carter', false, 406);
insert into book (id, name, is_available, author_id) values (33, 'Stockholm East (Stockholm Östra)', true, 170);
insert into book (id, name, is_available, author_id) values (34, 'Toto le héros', true, 385);
insert into book (id, name, is_available, author_id) values (35, 'Puppet Master: The Legacy (Puppet Master 8)', true, 69);
insert into book (id, name, is_available, author_id) values (36, 'Death Note', true, 165);
insert into book (id, name, is_available, author_id) values (37, 'Enter Nowhere', false, 85);
insert into book (id, name, is_available, author_id) values (38, 'Dark Forces (Harlequin)', false, 60);
insert into book (id, name, is_available, author_id) values (39, 'CSNY Déjà Vu', true, 420);
insert into book (id, name, is_available, author_id) values (40, 'Min så kallade pappa', false, 496);
insert into book (id, name, is_available, author_id) values (41, 'Puppet Masters, The', false, 209);
insert into book (id, name, is_available, author_id) values (42, 'The Roots of Heaven', true, 315);
insert into book (id, name, is_available, author_id) values (43, 'No habrá paz para los malvados', true, 261);
insert into book (id, name, is_available, author_id) values (44, 'Red Cliff (Chi bi)', false, 434);
insert into book (id, name, is_available, author_id) values (45, 'Detective, The (C+ jing taam)', true, 415);
insert into book (id, name, is_available, author_id) values (46, 'Bombshell', true, 69);
insert into book (id, name, is_available, author_id) values (47, 'Katze im Sack', false, 173);
insert into book (id, name, is_available, author_id) values (48, 'Hans (Kukkulan kuningas) ', false, 354);
insert into book (id, name, is_available, author_id) values (49, 'Donnie Darko', true, 121);
insert into book (id, name, is_available, author_id) values (50, 'Liberation of L.B. Jones, The', false, 302);
insert into book (id, name, is_available, author_id) values (51, 'Son of No One, The', true, 79);
insert into book (id, name, is_available, author_id) values (52, 'Battle Royale (Batoru rowaiaru)', true, 126);
insert into book (id, name, is_available, author_id) values (53, 'Ego', true, 10);
insert into book (id, name, is_available, author_id) values (54, 'Children Are Watching Us, The (Bambini ci guardano, I)', false, 101);
insert into book (id, name, is_available, author_id) values (55, 'Miami Rhapsody', true, 340);
insert into book (id, name, is_available, author_id) values (56, 'Two Queens and One Consort (Twee vorstinnen en een vorst)', false, 321);
insert into book (id, name, is_available, author_id) values (57, 'Stolen Children (Ladro di bambini, Il)', true, 192);
insert into book (id, name, is_available, author_id) values (58, 'Dread', false, 31);
insert into book (id, name, is_available, author_id) values (59, 'Marci X', false, 206);
insert into book (id, name, is_available, author_id) values (60, 'Cake Eaters, The', false, 475);
insert into book (id, name, is_available, author_id) values (61, 'Wanda', true, 202);
insert into book (id, name, is_available, author_id) values (62, 'Crane World (Mundo grúa)', true, 196);
insert into book (id, name, is_available, author_id) values (63, 'Second Time Around, The', false, 130);
insert into book (id, name, is_available, author_id) values (64, 'Dead Fury', true, 135);
insert into book (id, name, is_available, author_id) values (65, 'Adam Resurrected', false, 340);
insert into book (id, name, is_available, author_id) values (66, 'The Russian Novel', false, 340);
insert into book (id, name, is_available, author_id) values (67, 'Fish Story (Fisshu sutôrî)', true, 277);
insert into book (id, name, is_available, author_id) values (68, 'Lost Reels of Pancho Villa, The (Los rollos perdidos de Pancho Villa)', true, 258);
insert into book (id, name, is_available, author_id) values (69, 'Lourdes', false, 185);
insert into book (id, name, is_available, author_id) values (70, 'Pot O'' Gold', false, 435);
insert into book (id, name, is_available, author_id) values (71, 'Judith of Bethulia', true, 48);
insert into book (id, name, is_available, author_id) values (72, 'Oil, the Baby and the Transylvanians, The (Pruncul, petrolul si Ardelenii)', true, 89);
insert into book (id, name, is_available, author_id) values (73, 'Body Double', true, 399);
insert into book (id, name, is_available, author_id) values (74, 'Night of the Living Dead 3D', true, 217);
insert into book (id, name, is_available, author_id) values (75, 'Freaks', false, 333);
insert into book (id, name, is_available, author_id) values (76, 'O', false, 275);
insert into book (id, name, is_available, author_id) values (77, 'Ricky Rapper (Risto Räppääjä)', false, 357);
insert into book (id, name, is_available, author_id) values (78, 'Diplomatic Immunity (2009– )', true, 414);
insert into book (id, name, is_available, author_id) values (79, 'Five Obstructions, The (Fem benspænd, De)', false, 373);
insert into book (id, name, is_available, author_id) values (80, 'Halloween', false, 202);
insert into book (id, name, is_available, author_id) values (81, 'Casting By', true, 108);
insert into book (id, name, is_available, author_id) values (82, 'Boiling Point', false, 131);
insert into book (id, name, is_available, author_id) values (83, 'Destiny Turns on the Radio', true, 77);
insert into book (id, name, is_available, author_id) values (84, 'Parasite', false, 468);
insert into book (id, name, is_available, author_id) values (85, 'George Washington Slept Here', false, 51);
insert into book (id, name, is_available, author_id) values (86, 'Trader Horn', false, 198);
insert into book (id, name, is_available, author_id) values (87, 'Silent Night, Deadly Night 5: The Toy Maker', true, 494);
insert into book (id, name, is_available, author_id) values (88, 'Asterix: The Land of the Gods', false, 429);
insert into book (id, name, is_available, author_id) values (89, 'Out of the Blue', true, 217);
insert into book (id, name, is_available, author_id) values (90, 'They Live', true, 470);
insert into book (id, name, is_available, author_id) values (91, 'Fright Night', true, 362);
insert into book (id, name, is_available, author_id) values (92, 'Time Stood Still (Il tempo si è fermato)', false, 80);
insert into book (id, name, is_available, author_id) values (93, 'Last Airbender, The', false, 229);
insert into book (id, name, is_available, author_id) values (94, 'Wilderness', true, 464);
insert into book (id, name, is_available, author_id) values (95, 'Defenders of Riga', false, 284);
insert into book (id, name, is_available, author_id) values (96, 'Hey, Happy!', false, 58);
insert into book (id, name, is_available, author_id) values (97, 'Quadrophenia', false, 187);
insert into book (id, name, is_available, author_id) values (98, 'Ce que mes yeux ont vu', false, 10);
insert into book (id, name, is_available, author_id) values (99, 'Boulevard', true, 14);
insert into book (id, name, is_available, author_id) values (100, 'Ditirambo', false, 245);
insert into book (id, name, is_available, author_id) values (101, 'Ox-Bow Incident, The', true, 439);
insert into book (id, name, is_available, author_id) values (102, 'Out of Life (Hors la vie)', true, 203);
insert into book (id, name, is_available, author_id) values (103, 'Badge, The', true, 370);
insert into book (id, name, is_available, author_id) values (104, 'Innocence', false, 163);
insert into book (id, name, is_available, author_id) values (105, '貞子3D', true, 151);
insert into book (id, name, is_available, author_id) values (106, 'My Neighbors the Yamadas (Hôhokekyo tonari no Yamada-kun)', false, 36);
insert into book (id, name, is_available, author_id) values (107, 'Chicken, the Fish and the King Crab, The (El pollo, el pez y el cangrejo real)', false, 55);
insert into book (id, name, is_available, author_id) values (108, 'Tormented', true, 310);
insert into book (id, name, is_available, author_id) values (109, 'Tarantella', false, 302);
insert into book (id, name, is_available, author_id) values (110, 'Escanaba in da Moonlight', false, 235);
insert into book (id, name, is_available, author_id) values (111, 'Beyond the Forest', false, 235);
insert into book (id, name, is_available, author_id) values (112, 'Christmas Story 2, A', true, 265);
insert into book (id, name, is_available, author_id) values (113, '10 Questions for the Dalai Lama', true, 90);
insert into book (id, name, is_available, author_id) values (114, 'The Diary of Preston Plummer', true, 437);
insert into book (id, name, is_available, author_id) values (115, 'Unstoppable', false, 68);
insert into book (id, name, is_available, author_id) values (116, 'America Before Columbus', false, 300);
insert into book (id, name, is_available, author_id) values (117, 'Mo'' Money', true, 113);
insert into book (id, name, is_available, author_id) values (118, 'School of Flesh, The (École de la chair, L'')', false, 104);
insert into book (id, name, is_available, author_id) values (119, 'Castaway', false, 314);
insert into book (id, name, is_available, author_id) values (120, 'Ilsa, She Wolf of the SS', false, 291);
insert into book (id, name, is_available, author_id) values (121, 'Wide Awake', true, 84);
insert into book (id, name, is_available, author_id) values (122, 'Alarmist, The (a.k.a. Life During Wartime)', true, 484);
insert into book (id, name, is_available, author_id) values (123, 'Matrix Revolutions, The', true, 245);
insert into book (id, name, is_available, author_id) values (124, 'A Chinese in a Coma', true, 270);
insert into book (id, name, is_available, author_id) values (125, 'Civil Brand', true, 466);
insert into book (id, name, is_available, author_id) values (126, 'Herbie Rides Again', true, 334);
insert into book (id, name, is_available, author_id) values (127, 'Passengers', false, 360);
insert into book (id, name, is_available, author_id) values (128, 'Ungentlemanly Act, An', false, 17);
insert into book (id, name, is_available, author_id) values (129, 'All the Right Moves', false, 425);
insert into book (id, name, is_available, author_id) values (130, 'The Taking of Deborah Logan', false, 71);
insert into book (id, name, is_available, author_id) values (131, 'Tempest, The', true, 178);
insert into book (id, name, is_available, author_id) values (132, 'Time (Shi gan)', false, 311);
insert into book (id, name, is_available, author_id) values (133, 'Princess Blade, The (Shura Yukihime)', false, 27);
insert into book (id, name, is_available, author_id) values (134, 'Major Barbara', false, 484);
insert into book (id, name, is_available, author_id) values (135, 'T-Rex: Back to the Cretaceous', false, 473);
insert into book (id, name, is_available, author_id) values (136, 'Best Defense', true, 253);
insert into book (id, name, is_available, author_id) values (137, 'Family Guy Presents: It''s a Trap', false, 421);
insert into book (id, name, is_available, author_id) values (138, 'Good Ol'' Freda', true, 484);
insert into book (id, name, is_available, author_id) values (139, 'Wreck-It Ralph', true, 41);
insert into book (id, name, is_available, author_id) values (140, 'Adventure in Space and Time, An', false, 355);
insert into book (id, name, is_available, author_id) values (141, 'Watermelon Man', true, 90);
insert into book (id, name, is_available, author_id) values (142, 'Bruce Almighty', true, 32);
insert into book (id, name, is_available, author_id) values (143, 'Americanization of Emily, The', false, 430);
insert into book (id, name, is_available, author_id) values (144, 'Achilles and the Tortoise (Akiresu to kame)', false, 19);
insert into book (id, name, is_available, author_id) values (145, 'God Save My Shoes', true, 211);
insert into book (id, name, is_available, author_id) values (146, 'Interview with the Vampire: The Vampire Chronicles', false, 343);
insert into book (id, name, is_available, author_id) values (147, 'Four Bags Full', true, 156);
insert into book (id, name, is_available, author_id) values (148, 'Trick or Treat', false, 483);
insert into book (id, name, is_available, author_id) values (149, 'Not as a Stranger', true, 260);
insert into book (id, name, is_available, author_id) values (150, 'Stone', false, 211);
insert into book (id, name, is_available, author_id) values (151, 'Season of the Witch', false, 279);
insert into book (id, name, is_available, author_id) values (152, 'Freakin'' Beautiful World (Sairaan kaunis maailma)', true, 89);
insert into book (id, name, is_available, author_id) values (153, 'Dying Gaul, The', false, 126);
insert into book (id, name, is_available, author_id) values (154, 'Suicide Shop, The (Le magasin des suicides) ', true, 377);
insert into book (id, name, is_available, author_id) values (155, 'Believer, The', false, 18);
insert into book (id, name, is_available, author_id) values (156, 'Bon Voyage', false, 230);
insert into book (id, name, is_available, author_id) values (157, 'Smitty', false, 354);
insert into book (id, name, is_available, author_id) values (158, 'Root of All Evil?', true, 277);
insert into book (id, name, is_available, author_id) values (159, 'Murderous Maids (Blessures assassines, Les)', false, 16);
insert into book (id, name, is_available, author_id) values (160, 'Invasion of the Body Snatchers', false, 307);
insert into book (id, name, is_available, author_id) values (161, 'Ugly', false, 463);
insert into book (id, name, is_available, author_id) values (162, 'Nobody Knows (Dare mo shiranai)', true, 107);
insert into book (id, name, is_available, author_id) values (163, 'House', true, 166);
insert into book (id, name, is_available, author_id) values (164, 'Dangerous Man, A', false, 247);
insert into book (id, name, is_available, author_id) values (165, 'Just an American Boy', true, 103);
insert into book (id, name, is_available, author_id) values (166, 'Vares: The Kiss of Evil (Vares - Pahan suudelma)', true, 35);
insert into book (id, name, is_available, author_id) values (167, 'The Substitute 4: Failure Is Not an Option', true, 399);
insert into book (id, name, is_available, author_id) values (168, 'Oliver Twist', false, 429);
insert into book (id, name, is_available, author_id) values (169, 'Yumeji', false, 391);
insert into book (id, name, is_available, author_id) values (170, 'Zatoichi Meets the One-Armed Swordsman (Shin zatô Ichi: Yabure! Tôjin-ken) (Zatôichi 22)', false, 441);
insert into book (id, name, is_available, author_id) values (171, 'Rabbit', false, 249);
insert into book (id, name, is_available, author_id) values (172, 'Dracula (Bram Stoker''s Dracula)', false, 306);
insert into book (id, name, is_available, author_id) values (173, 'Ten Minutes Older: The Trumpet', true, 282);
insert into book (id, name, is_available, author_id) values (174, 'Maximum Conviction', true, 146);
insert into book (id, name, is_available, author_id) values (175, 'Tru Confessions', true, 237);
insert into book (id, name, is_available, author_id) values (176, 'Runaways, The', true, 417);
insert into book (id, name, is_available, author_id) values (177, 'Murph: The Protector', false, 253);
insert into book (id, name, is_available, author_id) values (178, 'Pledge This!', false, 407);
insert into book (id, name, is_available, author_id) values (179, 'Hunted, The', false, 302);
insert into book (id, name, is_available, author_id) values (180, 'Airbag', false, 248);
insert into book (id, name, is_available, author_id) values (181, 'Memories of Underdevelopment (Memorias del subdesarrollo)', true, 462);
insert into book (id, name, is_available, author_id) values (182, 'Intruder, The', false, 34);
insert into book (id, name, is_available, author_id) values (183, 'H.O.T.S.', false, 310);
insert into book (id, name, is_available, author_id) values (184, 'Lady for a Day', false, 441);
insert into book (id, name, is_available, author_id) values (185, 'Jackass 2.5', true, 145);
insert into book (id, name, is_available, author_id) values (186, 'Welcome Back, Mr. McDonald (Rajio no jikan)', true, 428);
insert into book (id, name, is_available, author_id) values (187, 'Regeneration', true, 32);
insert into book (id, name, is_available, author_id) values (188, 'Golden Thread, The (Subarnarekha)', false, 40);
insert into book (id, name, is_available, author_id) values (189, 'One Good Cop', false, 226);
insert into book (id, name, is_available, author_id) values (190, 'Silver Stallion (Silver Brumpy, The)', true, 452);
insert into book (id, name, is_available, author_id) values (191, 'Red Firecracker, Green Firecracker (Pao Da Shuang Deng)', true, 47);
insert into book (id, name, is_available, author_id) values (192, 'Masculin Féminin', true, 94);
insert into book (id, name, is_available, author_id) values (193, '17 Girls (17 filles)', false, 78);
insert into book (id, name, is_available, author_id) values (194, 'House on Telegraph Hill, The', true, 244);
insert into book (id, name, is_available, author_id) values (195, 'Good Earth, The', false, 231);
insert into book (id, name, is_available, author_id) values (196, 'Medea', false, 287);
insert into book (id, name, is_available, author_id) values (197, 'Wild Horse, Wild Ride', true, 318);
insert into book (id, name, is_available, author_id) values (198, 'Free Fall', false, 123);
insert into book (id, name, is_available, author_id) values (199, 'The Brass Legend', true, 174);
insert into book (id, name, is_available, author_id) values (200, 'Secrets of the Tribe', true, 373);
insert into book (id, name, is_available, author_id) values (201, 'Satan''s Sword (Daibosatsu tôge)', true, 91);
insert into book (id, name, is_available, author_id) values (202, 'Tammy', true, 387);
insert into book (id, name, is_available, author_id) values (203, 'Ironclad 2: Battle for Blood', true, 90);
insert into book (id, name, is_available, author_id) values (204, 'Trail of the Pink Panther', false, 337);
insert into book (id, name, is_available, author_id) values (205, 'Extreme Justice', false, 396);
insert into book (id, name, is_available, author_id) values (206, 'Time Machine, The', true, 223);
insert into book (id, name, is_available, author_id) values (207, 'Dancing in September', true, 15);
insert into book (id, name, is_available, author_id) values (208, 'Laughing Policeman, The', false, 87);
insert into book (id, name, is_available, author_id) values (209, 'Saint of Fort Washington, The', true, 301);
insert into book (id, name, is_available, author_id) values (210, 'Manufacturing Reality: Slavoj Zizek and the Reality of the Virtual (Slavoj Zizek: The Reality of the Virtual)', true, 266);
insert into book (id, name, is_available, author_id) values (211, 'El malvado Carabel', false, 29);
insert into book (id, name, is_available, author_id) values (212, 'World according to Ion B., The (Lumea vazuta de Ion B)', false, 187);
insert into book (id, name, is_available, author_id) values (213, 'Transmorphers', true, 196);
insert into book (id, name, is_available, author_id) values (214, 'Body of Evidence', false, 478);
insert into book (id, name, is_available, author_id) values (215, 'Back in the Day', false, 256);
insert into book (id, name, is_available, author_id) values (216, 'Music Man, The', true, 475);
insert into book (id, name, is_available, author_id) values (217, 'NeverEnding Story III, The', false, 190);
insert into book (id, name, is_available, author_id) values (218, 'My Wife, A Body to Love', true, 463);
insert into book (id, name, is_available, author_id) values (219, 'Service (Serbis)', true, 211);
insert into book (id, name, is_available, author_id) values (220, 'Wild, Wild Planet (I criminali della galassia)', false, 174);
insert into book (id, name, is_available, author_id) values (221, 'Mr. Pip', true, 414);
insert into book (id, name, is_available, author_id) values (222, 'Dhobi Ghat', true, 298);
insert into book (id, name, is_available, author_id) values (223, 'Claymation Christmas Celebration, A', true, 111);
insert into book (id, name, is_available, author_id) values (224, 'Chicago 10', false, 436);
insert into book (id, name, is_available, author_id) values (225, 'The Slap', true, 8);
insert into book (id, name, is_available, author_id) values (226, 'Kolya (Kolja)', true, 223);
insert into book (id, name, is_available, author_id) values (227, 'Big Broadcast of 1938, The', true, 411);
insert into book (id, name, is_available, author_id) values (228, 'Dead Man on Campus', false, 423);
insert into book (id, name, is_available, author_id) values (229, 'Raining Stones', false, 221);
insert into book (id, name, is_available, author_id) values (230, 'Aviator''s Wife, The (La femme de l''aviateur)', true, 171);
insert into book (id, name, is_available, author_id) values (231, 'Lumberjacking (Nuoruuteni savotat)', true, 380);
insert into book (id, name, is_available, author_id) values (232, 'Batman & Robin', true, 126);
insert into book (id, name, is_available, author_id) values (233, 'Kiss Me (Kyss Mig)', false, 210);
insert into book (id, name, is_available, author_id) values (234, 'Ruby Gentry', true, 362);
insert into book (id, name, is_available, author_id) values (235, 'Mr. Vampire (Geung si sin sang)', true, 65);
insert into book (id, name, is_available, author_id) values (236, 'Charlie''s Country', true, 486);
insert into book (id, name, is_available, author_id) values (237, 'Clonus Horror, The', true, 185);
insert into book (id, name, is_available, author_id) values (238, 'Virtuality', true, 344);
insert into book (id, name, is_available, author_id) values (239, 'The Mascot', true, 413);
insert into book (id, name, is_available, author_id) values (240, 'Torrid Zone', false, 260);
insert into book (id, name, is_available, author_id) values (241, 'Phone Call from a Stranger', true, 481);
insert into book (id, name, is_available, author_id) values (242, 'When Trumpets Fade', true, 260);
insert into book (id, name, is_available, author_id) values (243, 'She No Longer Talks, She Shoots', false, 416);
insert into book (id, name, is_available, author_id) values (244, 'Best Intentions, The (Den goda viljan)', false, 378);
insert into book (id, name, is_available, author_id) values (245, 'Adventures of Mary-Kate and Ashley, The: The Case of the Christmas Caper', true, 217);
insert into book (id, name, is_available, author_id) values (246, 'Cat Concerto, The', false, 146);
insert into book (id, name, is_available, author_id) values (247, 'Home', false, 451);
insert into book (id, name, is_available, author_id) values (248, 'Lizard, The (Marmoulak)', false, 93);
insert into book (id, name, is_available, author_id) values (249, 'Case 39', false, 427);
insert into book (id, name, is_available, author_id) values (250, 'Boys Life 2', false, 346);
insert into book (id, name, is_available, author_id) values (251, 'Melvin Goes to Dinner', false, 348);
insert into book (id, name, is_available, author_id) values (252, 'Ong-Bak: The Thai Warrior (Ong Bak)', false, 101);
insert into book (id, name, is_available, author_id) values (253, 'Blackboard Jungle', false, 268);
insert into book (id, name, is_available, author_id) values (254, 'Flower of My Secret, The (La flor de mi secreto)', false, 167);
insert into book (id, name, is_available, author_id) values (255, 'Battle: Los Angeles', false, 391);
insert into book (id, name, is_available, author_id) values (256, 'Rusty Knife (Sabita naifu)', false, 338);
insert into book (id, name, is_available, author_id) values (257, 'Ace Ventura: When Nature Calls', true, 129);
insert into book (id, name, is_available, author_id) values (258, 'Elvis: That''s the Way It Is', false, 432);
insert into book (id, name, is_available, author_id) values (259, 'Monk and the Fish, The (Le moine et le poisson)', true, 320);
insert into book (id, name, is_available, author_id) values (260, '6954 Kilometriä Kotiin', false, 479);
insert into book (id, name, is_available, author_id) values (261, 'Snowbeast', false, 405);
insert into book (id, name, is_available, author_id) values (262, 'Shopworn Angel, The', true, 228);
insert into book (id, name, is_available, author_id) values (263, 'Alive and Ticking (Ein Tick anders)', true, 229);
insert into book (id, name, is_available, author_id) values (264, 'Parasite', false, 149);
insert into book (id, name, is_available, author_id) values (265, 'Deadly Friend', false, 417);
insert into book (id, name, is_available, author_id) values (266, 'Canterville Ghost, The', true, 223);
insert into book (id, name, is_available, author_id) values (267, 'Lady Jane', true, 240);
insert into book (id, name, is_available, author_id) values (268, 'Replicant', true, 440);
insert into book (id, name, is_available, author_id) values (269, 'Why Not Me? (Pourquoi pas moi ?)', true, 400);
insert into book (id, name, is_available, author_id) values (270, 'Castles in the Sky', false, 106);
insert into book (id, name, is_available, author_id) values (271, 'First Love, Last Rites', false, 329);
insert into book (id, name, is_available, author_id) values (272, 'Diary of a Wimpy Kid: Dog Days', false, 446);
insert into book (id, name, is_available, author_id) values (273, 'Yes, Madam (a.k.a. Police Assassins) (a.k.a. In the Line of Duty 2) (Huang gu shi jie)', false, 105);
insert into book (id, name, is_available, author_id) values (274, 'Town Called Panic, A (Panique au village)', true, 353);
insert into book (id, name, is_available, author_id) values (275, 'xXx: State of the Union', true, 364);
insert into book (id, name, is_available, author_id) values (276, 'The Death and Life of Bobby Z', true, 331);
insert into book (id, name, is_available, author_id) values (277, 'Shooter, The', false, 160);
insert into book (id, name, is_available, author_id) values (278, 'Breaking Up', true, 120);
insert into book (id, name, is_available, author_id) values (279, 'For the Love of a Dog', false, 484);
insert into book (id, name, is_available, author_id) values (280, 'L''homme qui rit', true, 270);
insert into book (id, name, is_available, author_id) values (281, 'Mummy''s Curse, The', false, 334);
insert into book (id, name, is_available, author_id) values (282, 'Torrente 5: Operación Eurovegas', true, 151);
insert into book (id, name, is_available, author_id) values (283, 'Valentino: The Last Emperor', true, 181);
insert into book (id, name, is_available, author_id) values (284, 'Between Strangers', true, 468);
insert into book (id, name, is_available, author_id) values (285, 'Sun Don''t Shine', true, 169);
insert into book (id, name, is_available, author_id) values (286, 'Sexy Nights of the Living Dead', false, 451);
insert into book (id, name, is_available, author_id) values (287, 'Autobiography of Nicolae Ceausescu, The (Autobiografia lui Nicolae Ceausescu)', false, 337);
insert into book (id, name, is_available, author_id) values (288, 'Taming of the Shrew, The', false, 154);
insert into book (id, name, is_available, author_id) values (289, 'Simple Plan, A', true, 351);
insert into book (id, name, is_available, author_id) values (290, 'The Chatterley Affair', false, 132);
insert into book (id, name, is_available, author_id) values (291, 'The Little Polar Bear: Lars and the Little Tiger', true, 334);
insert into book (id, name, is_available, author_id) values (292, 'Battle of amfAR, The', false, 21);
insert into book (id, name, is_available, author_id) values (293, 'To Be Twenty', false, 130);
insert into book (id, name, is_available, author_id) values (294, 'People in Places', true, 90);
insert into book (id, name, is_available, author_id) values (295, '36 Hours', true, 86);
insert into book (id, name, is_available, author_id) values (296, 'Adventures of Sebastian Cole, The', true, 292);
insert into book (id, name, is_available, author_id) values (297, 'Woody Allen: A Documentary', true, 495);
insert into book (id, name, is_available, author_id) values (298, 'Grand Prix', true, 231);
insert into book (id, name, is_available, author_id) values (299, 'Steamboat Round the Bend', true, 197);
insert into book (id, name, is_available, author_id) values (300, 'Nightmare', true, 280);
insert into book (id, name, is_available, author_id) values (301, 'Permanent Vacation', false, 380);
insert into book (id, name, is_available, author_id) values (302, 'P.S.', true, 313);
insert into book (id, name, is_available, author_id) values (303, 'Night Passage', true, 439);
insert into book (id, name, is_available, author_id) values (304, 'It''s in the Water', false, 137);
insert into book (id, name, is_available, author_id) values (305, 'Black Narcissus', true, 110);
insert into book (id, name, is_available, author_id) values (306, 'Sound of Music, The', true, 296);
insert into book (id, name, is_available, author_id) values (307, 'Year of the Jellyfish (L''année des méduses)', true, 60);
insert into book (id, name, is_available, author_id) values (308, 'Hellraiser: Bloodline', true, 406);
insert into book (id, name, is_available, author_id) values (309, 'Crazy Kind of Love', true, 19);
insert into book (id, name, is_available, author_id) values (310, 'Rolling', true, 184);
insert into book (id, name, is_available, author_id) values (311, 'Joe Gould''s Secret', true, 365);
insert into book (id, name, is_available, author_id) values (312, 'Abominable Snowman, The (Abominable Snowman of the Himalayas, The)', true, 117);
insert into book (id, name, is_available, author_id) values (313, 'Delicate Balance, A', false, 474);
insert into book (id, name, is_available, author_id) values (314, 'Darkness', false, 164);
insert into book (id, name, is_available, author_id) values (315, 'Six Days', false, 269);
insert into book (id, name, is_available, author_id) values (316, 'PressPausePlay', true, 112);
insert into book (id, name, is_available, author_id) values (317, 'Side Out', true, 271);
insert into book (id, name, is_available, author_id) values (318, 'Days of Being Wild (A Fei jingjyuhn)', false, 241);
insert into book (id, name, is_available, author_id) values (319, 'Ali G Indahouse', true, 490);
insert into book (id, name, is_available, author_id) values (320, 'Big Trouble', true, 236);
insert into book (id, name, is_available, author_id) values (321, 'Grotesque', true, 100);
insert into book (id, name, is_available, author_id) values (322, 'Smoking/No Smoking', false, 112);
insert into book (id, name, is_available, author_id) values (323, 'Ten', false, 332);
insert into book (id, name, is_available, author_id) values (324, 'Suspicion', true, 145);
insert into book (id, name, is_available, author_id) values (325, 'Firaaq', false, 489);
insert into book (id, name, is_available, author_id) values (326, 'Rowing with the Wind (Remando al viento)', false, 146);
insert into book (id, name, is_available, author_id) values (327, 'Burt''s Buzz', false, 445);
insert into book (id, name, is_available, author_id) values (328, 'She Monkeys', false, 388);
insert into book (id, name, is_available, author_id) values (329, 'Maytime', true, 257);
insert into book (id, name, is_available, author_id) values (330, '2012: Supernova', true, 422);
insert into book (id, name, is_available, author_id) values (331, 'Ursul', false, 392);
insert into book (id, name, is_available, author_id) values (332, 'RFK Must Die: The Assassination of Bobby Kennedy', false, 318);
insert into book (id, name, is_available, author_id) values (333, 'Last Resort (National Lampoon''s Last Resort)', true, 238);
insert into book (id, name, is_available, author_id) values (334, 'Zona Zamfirova', true, 445);
insert into book (id, name, is_available, author_id) values (335, 'Bride Comes Home, The', true, 95);
insert into book (id, name, is_available, author_id) values (336, 'Siegfried & Roy: The Magic Box', true, 177);
insert into book (id, name, is_available, author_id) values (337, 'Dillinger', true, 431);
insert into book (id, name, is_available, author_id) values (338, 'Katt Williams: The Pimp Chronicles Pt. 1', true, 491);
insert into book (id, name, is_available, author_id) values (339, 'Aladin', true, 56);
insert into book (id, name, is_available, author_id) values (340, 'Great Ecstasy of Woodcarver Steiner, The (Große Ekstase des Bildschnitzers Steiner, Die)', true, 204);
insert into book (id, name, is_available, author_id) values (341, 'Bolero (Uns et les autres, Les)', true, 392);
insert into book (id, name, is_available, author_id) values (342, 'Dawn Patrol, The (Flight Commander)', true, 15);
insert into book (id, name, is_available, author_id) values (343, 'Lake Placid', false, 205);
insert into book (id, name, is_available, author_id) values (344, 'Zombie Holocaust (a.k.a. Doctor Butcher M.D.) (Zombi Holocaust)', true, 62);
insert into book (id, name, is_available, author_id) values (345, 'I Drink Your Blood', true, 408);
insert into book (id, name, is_available, author_id) values (346, 'Reality of Love, The (I Want to Marry Ryan Banks)', false, 441);
insert into book (id, name, is_available, author_id) values (347, 'Teenage', true, 470);
insert into book (id, name, is_available, author_id) values (348, 'After Innocence', true, 113);
insert into book (id, name, is_available, author_id) values (349, 'Dream Catcher, The', true, 267);
insert into book (id, name, is_available, author_id) values (350, 'Who Killed Bambi? (Qui a tué Bambi?)', false, 213);
insert into book (id, name, is_available, author_id) values (351, 'House on Haunted Hill', false, 338);
insert into book (id, name, is_available, author_id) values (352, 'Adult World', true, 336);
insert into book (id, name, is_available, author_id) values (353, 'Black Sun (Kuroi taiyô)', false, 298);
insert into book (id, name, is_available, author_id) values (354, 'Fine Pair, A (Ruba al prossimo tuo)', false, 24);
insert into book (id, name, is_available, author_id) values (355, 'Wedding Party, The', false, 315);
insert into book (id, name, is_available, author_id) values (356, 'Last Days, The (Últimos días, Los)', true, 232);
insert into book (id, name, is_available, author_id) values (357, 'Boxing Helena', false, 282);
insert into book (id, name, is_available, author_id) values (358, 'Pelle Svanslös', false, 19);
insert into book (id, name, is_available, author_id) values (359, 'Reel Bad Arabs: How Hollywood Vilifies a People', false, 323);
insert into book (id, name, is_available, author_id) values (360, 'Over Your Dead Body', true, 482);
insert into book (id, name, is_available, author_id) values (361, 'Angel''s Leap', false, 479);
insert into book (id, name, is_available, author_id) values (362, 'Price of Glory', true, 94);
insert into book (id, name, is_available, author_id) values (363, 'Chelsea on the Rocks', false, 457);
insert into book (id, name, is_available, author_id) values (364, 'Bring It On: In It To Win It', true, 385);
insert into book (id, name, is_available, author_id) values (365, 'Gamera vs. Jiger', false, 336);
insert into book (id, name, is_available, author_id) values (366, 'Verlorene, Der (Lost One, The)', false, 346);
insert into book (id, name, is_available, author_id) values (367, 'Mother Küsters Goes to Heaven (Mutter Küsters'' Fahrt zum Himmel)', true, 321);
insert into book (id, name, is_available, author_id) values (368, 'Clown, The', false, 89);
insert into book (id, name, is_available, author_id) values (369, 'Le Week-End', false, 275);
insert into book (id, name, is_available, author_id) values (370, 'Lost Battalion, The', false, 249);
insert into book (id, name, is_available, author_id) values (371, 'Beautiful Kate', true, 362);
insert into book (id, name, is_available, author_id) values (372, 'Escape from L.A.', true, 289);
insert into book (id, name, is_available, author_id) values (373, 'Floating', true, 202);
insert into book (id, name, is_available, author_id) values (374, 'Last Hurrah for Chivalry (Hao xia)', true, 484);
insert into book (id, name, is_available, author_id) values (375, 'Imaginary Crimes', true, 279);
insert into book (id, name, is_available, author_id) values (376, 'Cool Air', true, 289);
insert into book (id, name, is_available, author_id) values (377, 'First Beautiful Thing, The (La prima cosa bella)', true, 437);
insert into book (id, name, is_available, author_id) values (378, 'Growing Pains', true, 75);
insert into book (id, name, is_available, author_id) values (379, 'Licence to Kill', false, 183);
insert into book (id, name, is_available, author_id) values (380, 'Man on the Train (Homme du train, L'')', false, 274);
insert into book (id, name, is_available, author_id) values (381, 'Unrest', false, 323);
insert into book (id, name, is_available, author_id) values (382, 'Washington Square', true, 15);
insert into book (id, name, is_available, author_id) values (383, 'Mirrors 2', true, 70);
insert into book (id, name, is_available, author_id) values (384, 'Dentist, The', false, 9);
insert into book (id, name, is_available, author_id) values (385, 'Pokémon the Movie: Black - Victini and Reshiram', true, 103);
insert into book (id, name, is_available, author_id) values (386, 'Hearts and Minds', true, 448);
insert into book (id, name, is_available, author_id) values (387, 'Big Miracle', true, 387);
insert into book (id, name, is_available, author_id) values (388, 'The Body', false, 85);
insert into book (id, name, is_available, author_id) values (389, 'High Tension (Haute tension) (Switchblade Romance)', true, 398);
insert into book (id, name, is_available, author_id) values (390, 'Donovan''s Brain', true, 406);
insert into book (id, name, is_available, author_id) values (391, 'Confessions of a Teenage Drama Queen', true, 229);
insert into book (id, name, is_available, author_id) values (392, 'Dancers', true, 461);
insert into book (id, name, is_available, author_id) values (393, 'Here Comes the Navy', true, 209);
insert into book (id, name, is_available, author_id) values (394, 'Dossier 51 (Dossier 51, Le)', false, 10);
insert into book (id, name, is_available, author_id) values (395, 'Night in the Life of Jimmy Reardon, A', false, 176);
insert into book (id, name, is_available, author_id) values (396, 'Closer', true, 34);
insert into book (id, name, is_available, author_id) values (397, 'Poison', true, 12);
insert into book (id, name, is_available, author_id) values (398, 'Oklahoma Kid, The', false, 57);
insert into book (id, name, is_available, author_id) values (399, 'Caged Heat', true, 223);
insert into book (id, name, is_available, author_id) values (400, 'Umberto D.', true, 342);
insert into book (id, name, is_available, author_id) values (401, 'Standing Still', true, 219);
insert into book (id, name, is_available, author_id) values (402, 'W.W. and the Dixie Dancekings', true, 434);
insert into book (id, name, is_available, author_id) values (403, 'Story of Maths, The', false, 358);
insert into book (id, name, is_available, author_id) values (404, 'Printed Rainbow', true, 422);
insert into book (id, name, is_available, author_id) values (405, 'Walter', false, 426);
insert into book (id, name, is_available, author_id) values (406, 'Gone Baby Gone', true, 177);
insert into book (id, name, is_available, author_id) values (407, 'Body of Evidence', false, 155);
insert into book (id, name, is_available, author_id) values (408, 'Bloodhounds of Broadway', true, 336);
insert into book (id, name, is_available, author_id) values (409, 'Den tatuerade änkan (Tattooed Widow, The) ', false, 452);
insert into book (id, name, is_available, author_id) values (410, 'Today''s Special', false, 282);
insert into book (id, name, is_available, author_id) values (411, 'E Aí... Comeu?', false, 178);
insert into book (id, name, is_available, author_id) values (412, 'Fallen Sparrow, The', false, 339);
insert into book (id, name, is_available, author_id) values (413, 'Any Day Now', true, 500);
insert into book (id, name, is_available, author_id) values (414, 'Day of the Dead', false, 75);
insert into book (id, name, is_available, author_id) values (415, 'Fear[s] of the Dark (Peur[s] du noir)', true, 471);
insert into book (id, name, is_available, author_id) values (416, 'The Kiss of Her Flesh', false, 35);
insert into book (id, name, is_available, author_id) values (417, 'White Water Summer', true, 11);
insert into book (id, name, is_available, author_id) values (418, 'Flash of Genius', true, 313);
insert into book (id, name, is_available, author_id) values (419, 'Aries Spears: Hollywood, Look I''m Smiling', false, 481);
insert into book (id, name, is_available, author_id) values (420, 'Hidden Agenda', true, 202);
insert into book (id, name, is_available, author_id) values (421, 'That Cold Day in the Park', false, 364);
insert into book (id, name, is_available, author_id) values (422, 'Terror on a Train (Time Bomb)', false, 82);
insert into book (id, name, is_available, author_id) values (423, 'Beautiful Losers', false, 443);
insert into book (id, name, is_available, author_id) values (424, 'Heldorado', true, 155);
insert into book (id, name, is_available, author_id) values (425, 'Fast and the Furious, The', false, 326);
insert into book (id, name, is_available, author_id) values (426, 'Funny Games U.S.', true, 111);
insert into book (id, name, is_available, author_id) values (427, 'Täynnä Tarmoa', true, 389);
insert into book (id, name, is_available, author_id) values (428, 'Clerks II', false, 54);
insert into book (id, name, is_available, author_id) values (429, 'Crash Reel, The', false, 488);
insert into book (id, name, is_available, author_id) values (430, 'Mechanic, The', false, 345);
insert into book (id, name, is_available, author_id) values (431, 'Chain Reaction', false, 113);
insert into book (id, name, is_available, author_id) values (432, 'Horse''s Mouth, The', false, 453);
insert into book (id, name, is_available, author_id) values (433, 'Distant Thunder', false, 61);
insert into book (id, name, is_available, author_id) values (434, 'Nick of Time', true, 74);
insert into book (id, name, is_available, author_id) values (435, 'Lizard in a Woman''s Skin, A (Lucertola con la pelle di donna, Una)', true, 19);
insert into book (id, name, is_available, author_id) values (436, 'Defying Gravity', false, 17);
insert into book (id, name, is_available, author_id) values (437, 'Funky Forest: The First Contact', true, 350);
insert into book (id, name, is_available, author_id) values (438, 'Hysteria: The Def Leppard Story', false, 448);
insert into book (id, name, is_available, author_id) values (439, 'Cockneys vs Zombies', false, 162);
insert into book (id, name, is_available, author_id) values (440, 'They Live by Night', false, 262);
insert into book (id, name, is_available, author_id) values (441, 'Purge, The', true, 93);
insert into book (id, name, is_available, author_id) values (442, 'Two Weeks in September', false, 177);
insert into book (id, name, is_available, author_id) values (443, 'Jurassic Park', true, 199);
insert into book (id, name, is_available, author_id) values (444, 'The Great Northfield Minnesota Raid', true, 356);
insert into book (id, name, is_available, author_id) values (445, 'Friend Is a Treasure, A (Chi Trova Un Amico, Trova un Tesoro) (Who Finds a Friend Finds a Treasure)', false, 112);
insert into book (id, name, is_available, author_id) values (446, 'Great War, The (Grande guerra, La)', false, 342);
insert into book (id, name, is_available, author_id) values (447, 'Westworld', true, 277);
insert into book (id, name, is_available, author_id) values (448, 'Navy Seals', true, 135);
insert into book (id, name, is_available, author_id) values (449, 'Night and Fog (Nuit et brouillard)', true, 63);
insert into book (id, name, is_available, author_id) values (450, 'Blondie Knows Best', false, 280);
insert into book (id, name, is_available, author_id) values (451, 'Blackadder''s Christmas Carol', false, 222);
insert into book (id, name, is_available, author_id) values (452, 'Used People', true, 44);
insert into book (id, name, is_available, author_id) values (453, 'Official Story, The (La historia oficial)', false, 161);
insert into book (id, name, is_available, author_id) values (454, 'So Evil, So Young', false, 340);
insert into book (id, name, is_available, author_id) values (455, 'First Sunday', false, 444);
insert into book (id, name, is_available, author_id) values (456, 'Raven, The', true, 294);
insert into book (id, name, is_available, author_id) values (457, 'My Lucky Stars (Fuk sing go jiu)', true, 222);
insert into book (id, name, is_available, author_id) values (458, 'Enchanted', false, 161);
insert into book (id, name, is_available, author_id) values (459, 'Candyman 3: Day of the Dead', false, 374);
insert into book (id, name, is_available, author_id) values (460, 'Suture', true, 349);
insert into book (id, name, is_available, author_id) values (461, 'Ace Ventura: Pet Detective', true, 385);
insert into book (id, name, is_available, author_id) values (462, '7 Virgins (7 vírgenes)', false, 333);
insert into book (id, name, is_available, author_id) values (463, 'Something to Talk About', true, 305);
insert into book (id, name, is_available, author_id) values (464, 'Cracks', false, 338);
insert into book (id, name, is_available, author_id) values (465, 'Hijacking, A (Kapringen)', false, 296);
insert into book (id, name, is_available, author_id) values (466, 'Tribute', true, 342);
insert into book (id, name, is_available, author_id) values (467, 'Incredible Melting Man, The', true, 372);
insert into book (id, name, is_available, author_id) values (468, 'Anchorman 2: The Legend Continues', false, 102);
insert into book (id, name, is_available, author_id) values (469, 'Marvellous', true, 108);
insert into book (id, name, is_available, author_id) values (470, 'Heartless', false, 419);
insert into book (id, name, is_available, author_id) values (471, 'Fast, Cheap & Out of Control', true, 416);
insert into book (id, name, is_available, author_id) values (472, 'Dear Frankie', true, 16);
insert into book (id, name, is_available, author_id) values (473, 'Superweib, Das', false, 146);
insert into book (id, name, is_available, author_id) values (474, 'Mr. Nice', false, 490);
insert into book (id, name, is_available, author_id) values (475, '13/13/13', true, 241);
insert into book (id, name, is_available, author_id) values (476, 'American Pastime', true, 199);
insert into book (id, name, is_available, author_id) values (477, 'The Princess Comes Across', false, 181);
insert into book (id, name, is_available, author_id) values (478, 'Fireworks Wednesday (Chaharshanbe-soori)', false, 281);
insert into book (id, name, is_available, author_id) values (479, 'Across the Universe', true, 241);
insert into book (id, name, is_available, author_id) values (480, 'Afternoon Delight', false, 348);
insert into book (id, name, is_available, author_id) values (481, 'Just Like a Woman', false, 109);
insert into book (id, name, is_available, author_id) values (482, 'Zapped!', false, 150);
insert into book (id, name, is_available, author_id) values (483, 'Wake of the Red Witch', false, 363);
insert into book (id, name, is_available, author_id) values (484, 'Invictus', true, 22);
insert into book (id, name, is_available, author_id) values (485, 'From Above', false, 465);
insert into book (id, name, is_available, author_id) values (486, 'Cobra Verde', false, 238);
insert into book (id, name, is_available, author_id) values (487, 'Outlaw', false, 253);
insert into book (id, name, is_available, author_id) values (488, 'Ringers: Lord of the Fans', true, 225);
insert into book (id, name, is_available, author_id) values (489, 'Onmyoji (Onmyoji: The Yin Yang Master)', false, 417);
insert into book (id, name, is_available, author_id) values (490, 'The Outsider', false, 487);
insert into book (id, name, is_available, author_id) values (491, 'Prêt à tout', false, 497);
insert into book (id, name, is_available, author_id) values (492, 'Don''t Go In the Woods', false, 121);
insert into book (id, name, is_available, author_id) values (493, 'Devil''s Advocate, The', true, 199);
insert into book (id, name, is_available, author_id) values (494, 'War of the Dead - Stone''s War ', true, 307);
insert into book (id, name, is_available, author_id) values (495, 'Feuer, Eis & Dosenbier', false, 385);
insert into book (id, name, is_available, author_id) values (496, 'Detective Story', false, 20);
insert into book (id, name, is_available, author_id) values (497, 'The Man They Could Not Hang', false, 107);
insert into book (id, name, is_available, author_id) values (498, 'Scarface', true, 184);
insert into book (id, name, is_available, author_id) values (499, 'Lookout, The', false, 294);
insert into book (id, name, is_available, author_id) values (500, 'Neighbors', true, 452);